services:
  - type: web
    name: Student-Placement-Predictor_demo
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.11
